<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>8a6a0714-c123-47e8-9d19-eb9b248e18cc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.2.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetGoods.Recipes.Infra.CrossCutting.Bus\SweetGoods.Recipes.Infra.CrossCutting.Bus.csproj" />
    <ProjectReference Include="..\SweetGoods.Recipes.Infra.CrossCutting.IoC\SweetGoods.Recipes.Infra.CrossCutting.IoC.csproj" />
    <ProjectReference Include="..\SweetGoods.Recipes.Infra.Data\SweetGoods.Recipes.Infra.Data.csproj" />
  </ItemGroup>

</Project>
