<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Validations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetGoods.Recipes.Domain.Core\SweetGoods.Recipes.Domain.Core.csproj" />
    <ProjectReference Include="..\SweetGoods.Recipes.Infra.CrossCutting.Bus\SweetGoods.Recipes.Infra.CrossCutting.Bus.csproj" />
  </ItemGroup>

</Project>
