<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EventSourcedNormalizers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SweetGoods.Recipes.Domain\SweetGoods.Recipes.Domain.csproj" />
    <ProjectReference Include="..\SweetGoods.Recipes.Infra.Data\SweetGoods.Recipes.Infra.Data.csproj" />
  </ItemGroup>

</Project>
