// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SweetGoods.Recipes.Domain.Enums;
using SweetGoods.Recipes.Infra.Data.Context;
using System;

namespace SweetGoods.Recipes.Infra.Data.Migrations
{
    [DbContext(typeof(SweetGoodsRecipesContext))]
    [Migration("20180506173205_InitialBaseSetup")]
    partial class InitialBaseSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryType");

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("SoftDeleted");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.CookingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("time(7)");

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RecipeId");

                    b.Property<bool>("SoftDeleted");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("CookingMethods");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.CookingMethodIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CookingMethodId");

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IngredientId");

                    b.Property<decimal>("Measure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasureType")
                        .HasColumnType("int");

                    b.Property<string>("Usage")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CookingMethodId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CookingMethodIngredients");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.CookingStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CookingMethodId");

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StepAction")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StepNumber");

                    b.HasKey("Id");

                    b.HasIndex("CookingMethodId");

                    b.ToTable("CookingSteps");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("SoftDeleted");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("SoftDeleted");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.RecipeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<int>("IncrementId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeCategories");
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.Category", b =>
                {
                    b.OwnsOne("SweetGoods.Recipes.Domain.Models.ValueObjects.DescriptionValueObject", "Description", b1 =>
                        {
                            b1.Property<Guid>("CategoryId");

                            b1.Property<string>("Description")
                                .HasColumnName("Description")
                                .HasColumnType("nvarchar(500)")
                                .HasMaxLength(500);

                            b1.ToTable("Categories");

                            b1.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Category")
                                .WithOne("Description")
                                .HasForeignKey("SweetGoods.Recipes.Domain.Models.ValueObjects.DescriptionValueObject", "CategoryId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("SweetGoods.Recipes.Domain.Models.ValueObjects.NameValueObject", "Name", b1 =>
                        {
                            b1.Property<Guid>("CategoryId");

                            b1.Property<string>("Name")
                                .HasColumnName("Name")
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.ToTable("Categories");

                            b1.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Category")
                                .WithOne("Name")
                                .HasForeignKey("SweetGoods.Recipes.Domain.Models.ValueObjects.NameValueObject", "CategoryId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.CookingMethod", b =>
                {
                    b.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Recipe", "Recipe")
                        .WithMany("CookingMethods")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SweetGoods.Recipes.Domain.Models.ValueObjects.DescriptionValueObject", "Description", b1 =>
                        {
                            b1.Property<Guid?>("CookingMethodId");

                            b1.Property<string>("Description")
                                .HasColumnName("Description")
                                .HasColumnType("nvarchar(500)")
                                .HasMaxLength(500);

                            b1.ToTable("CookingMethods");

                            b1.HasOne("SweetGoods.Recipes.Domain.Models.Entities.CookingMethod")
                                .WithOne("Description")
                                .HasForeignKey("SweetGoods.Recipes.Domain.Models.ValueObjects.DescriptionValueObject", "CookingMethodId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.CookingMethodIngredient", b =>
                {
                    b.HasOne("SweetGoods.Recipes.Domain.Models.Entities.CookingMethod", "CookingMethod")
                        .WithMany("Ingredients")
                        .HasForeignKey("CookingMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.CookingStep", b =>
                {
                    b.HasOne("SweetGoods.Recipes.Domain.Models.Entities.CookingMethod")
                        .WithMany("Steps")
                        .HasForeignKey("CookingMethodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.Ingredient", b =>
                {
                    b.OwnsOne("SweetGoods.Recipes.Domain.Models.ValueObjects.NameValueObject", "Name", b1 =>
                        {
                            b1.Property<Guid?>("IngredientId");

                            b1.Property<string>("Name")
                                .HasColumnName("Name")
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.ToTable("Ingredients");

                            b1.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Ingredient")
                                .WithOne("Name")
                                .HasForeignKey("SweetGoods.Recipes.Domain.Models.ValueObjects.NameValueObject", "IngredientId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.Recipe", b =>
                {
                    b.OwnsOne("SweetGoods.Recipes.Domain.Models.ValueObjects.DescriptionValueObject", "Description", b1 =>
                        {
                            b1.Property<Guid?>("RecipeId");

                            b1.Property<string>("Description")
                                .HasColumnName("Description")
                                .HasColumnType("nvarchar(500)")
                                .HasMaxLength(500);

                            b1.ToTable("Recipes");

                            b1.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Recipe")
                                .WithOne("Description")
                                .HasForeignKey("SweetGoods.Recipes.Domain.Models.ValueObjects.DescriptionValueObject", "RecipeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("SweetGoods.Recipes.Domain.Models.ValueObjects.NameValueObject", "Name", b1 =>
                        {
                            b1.Property<Guid?>("RecipeId");

                            b1.Property<string>("Name")
                                .HasColumnName("Name")
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.ToTable("Recipes");

                            b1.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Recipe")
                                .WithOne("Name")
                                .HasForeignKey("SweetGoods.Recipes.Domain.Models.ValueObjects.NameValueObject", "RecipeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("SweetGoods.Recipes.Domain.Models.Entities.RecipeCategory", b =>
                {
                    b.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SweetGoods.Recipes.Domain.Models.Entities.Recipe", "Recipe")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
